### ISSUE TITLE
Map image in signature 1, page iii is clipped at the bottom (when printing)

### ISSUE THREAD

**Issue by Zweistein2022** [Nightsky770/treasureislandforbinders#1]
In the A4 version (my preference) there seems to be a written line missing due to the map being clipped at the bottom of the page. The line shows on the Letter signature but then it is outside the (laser) printable area when printed on 100%.

Is it possible that the map image is resized so the map bottom has the same clearance from the page bottom as the map top currently has to the page top?

Thanks a lot for your amazing work.

**Comment by Nightsky770** [comment]
Fixed! Still working on getting it vertically centered, but it's no longer
cut off in a4.

**Comment by Zweistein2022** [comment]
Thanks for the super fast fix! I will close the issue since the A4 is fixed now and can be printed without information looking clipped of. I will keep an eye out for the centred map update.

**Comment by Nightsky770** [comment]
Should now be centered.

**Comment by Zweistein2022** [comment]
Much obliged!
