### ISSUE TITLE
Image file missing

### ISSUE THREAD

**Issue by zbrasseaux** [Nightsky770/treasureislandforbinders#2]
In file `./source/treasureislandtop.tex`, on line 187, ` \includepdf[width=\textwidth]{timapcolor.png}`, the mentioned file cannot be found in the `./source/images` directory. 

Furthermore, ﻿`chap25strikecolors.png` and `chap2colordog.png` are the only image files to mention color in the name.

Excellent work on the project, really appreciate this stuff!

**Comment by Nightsky770** [comment]
Added it--I think I just overlooked it.

However, I'm not super clear what you mean about chap25strikecolors.png and chap2colordog.png being the only image files to mention color. Should they... not?

**Comment by zbrasseaux** [comment]
sorry for that lol, i was just making sure i did my due diligence to make sure i wasn't overlooking it
